window.SEATING_GUESTS = [
  { first: "Quiana", last: "Reynolds", table: "1" },
  { first: "Bryan", last: "Reynolds", table: "1" },
  { first: "DeVaughn", last: "Akoon Purcell", table: "1" },
  { first: "Audrey", last: "Akoon Purcell", table: "1" },
  { first: "Justin", last: "Anderson", table: "1" },
  { first: "Shannon", last: "Oneil", table: "1" },
  { first: "McKenzie", last: "Anderson", table: "1" },
  { first: "Paul", last: "Akoon", table: "1" },
  { first: "DeJah", last: "Akoon", table: "1" },
  { first: "Destyne", last: "Akoon", table: "1" },
  { first: "Donovyn", last: "Akoon", table: "1" },
  { first: "Minchy", last: "Estime", table: "1" },
  { first: "Ashley", last: "Malivert", table: "1" },
  { first: "Chantel", last: "McKnight", table: "1" },

  { first: "Leysa", last: "Purcell", table: "2" },
  { first: "Dean", last: "Ible", table: "2" },
  { first: "Frantz", last: "Dutes", table: "2" },
  { first: "Glennis", last: "Dutes", table: "2" },
  { first: "Wimi", last: "Cummings", table: "2" },
  { first: "Donna", last: "Cummings", table: "2" },
  { first: "Ken", last: "Purcell", table: "2" },
  { first: "Faye", last: "Purcell", table: "2" },
  { first: "Kheon", last: "Jones", table: "2" },
  { first: "Khalani", last: "Purcell", table: "2" },
  { first: "Kathy", last: "Telfair", table: "2" },
  { first: "Rita", last: "Saldana", table: "2" },
  { first: "Darron", last: "Saldana", table: "2" },
  { first: "Kesia", last: "Purcell", table: "2" },

  { first: "Cyndia", last: "Millender", table: "3" },
  { first: "Marcus", last: "Millender", table: "3" },
  { first: "Kress", last: "Estime", table: "3" },
  { first: "Grazuela", last: "Pierre", table: "3" },
  { first: "Lisa", last: "Estime", table: "3" },
  { first: "Stevencia", last: "Estime", table: "3" },
  { first: "Vernet", last: "Estime", table: "3" },
  { first: "Alicia", last: "Estime", table: "3" },
  { first: "Luzette", last: "Estime", table: "3" },

  { first: "Andy", last: "Elizaire", table: "4" },
  { first: "Shanelle", last: "Elizaire", table: "4" },
  { first: "Jose", last: "Pierre", table: "4" },
  { first: "Kim", last: "Taylor", table: "4" },
  { first: "Angeline", last: "Antonie", table: "4" },
  { first: "Jessie", last: "Antonie", table: "4" },
  { first: "Michael", last: "Rivera", table: "4" },
  { first: "Stephanie", last: "Chery", table: "4" },
  { first: "Sebastian", last: "Singh", table: "4" },

  { first: "Any", last: "Hughes-Castillo", table: "5" },
  { first: "Diego", last: "Castillo", table: "5" },
  { first: "Melanie", last: "Gaynor", table: "5" },
  { first: "Sean", last: "Gaynor", table: "5" },
  { first: "Xhen", last: "Kamberaj", table: "5" },
  { first: "Stefano", last: "Veliz", table: "5" },
  { first: "Gisselle", last: "Bermudez", table: "5" },
  { first: "Josh", last: "Ingram", table: "5" },

  { first: "Shama", last: "Exanor", table: "6 & 7" },
  { first: "Ruth", last: "Exanor", table: "6 & 7" },
  { first: "Myderline", last: "Exanor", table: "6 & 7" },
  { first: "Sabine", last: "Pierre", table: "6 & 7" },
  { first: "Sandry", last: "Pierre", table: "6 & 7" },
  { first: "Cleomen", last: "Pierre", table: "6 & 7" },
  { first: "Jane", last: "Estime", table: "6 & 7" },
  { first: "Gerda", last: "Estime", table: "6 & 7" },
  { first: "Daphney", last: "Chevry", table: "6 & 7" },
  { first: "Esther", last: "Petit", table: "6 & 7" },
  { first: "Luder", last: "Exanor", table: "6 & 7" },
  { first: "Myrland", last: "Exanor", table: "6 & 7" },
  { first: "Meranda", last: "", table: "6 & 7" },
  { first: "Gloria", last: "Plamer", table: "6 & 7" },
  { first: "Loren", last: "Aqui", table: "6 & 7" },
  { first: "Andre", last: "", table: "6 & 7" },
  { first: "Lordine", last: "Destin", table: "6 & 7" },
  { first: "Hucen", last: "Destin", table: "6 & 7" },

  { first: "Crystle", last: "Stewart", table: "8" },
  { first: "Naron", last: "Stewart", table: "8" },
  { first: "Gary", last: "Williams", table: "8" },
  { first: "Soyoung", last: "", table: "8" },
  { first: "Shavonne", last: "Williams", table: "8" },
  { first: "Milan", last: "Mckinney", table: "8" },
  { first: "Jasmine", last: "Jones", table: "8" },
  { first: "Anthony", last: "Pierce", table: "8" },
  { first: "Chris", last: "Reid", table: "8" },

  { first: "Krissy", last: "Williams", table: "9" },
  { first: "Corey", last: "Williams", table: "9" },
  { first: "Fabby", last: "Delivrance", table: "9" },
  { first: "Wenky Dizzle", last: "Delivrance", table: "9" },
  { first: "Amari", last: "Hamilton", table: "9" },
  { first: "Jessica", last: "Odoh", table: "9" },
  { first: "Lexxton", last: "Edwards", table: "9" },
  { first: "Andrea", last: "Cummings", table: "9" },
  { first: "Travon", last: "Terrell", table: "9" },

  { first: "Ben", last: "Jeudy", table: "10" },
  { first: "Brian", last: "Dusape", table: "10" },
  { first: "Erickben", last: "Elizaire", table: "10" },
  { first: "Janice", last: "Elizaire", table: "10" },
  { first: "Keroline", last: "Francois", table: "10" },
  { first: "Shwana", last: "Jean-Gilles", table: "10" },
  { first: "Kelcey", last: "Mallory", table: "10" },
  { first: "Van", last: "Carswell", table: "10" },
  { first: "Joyce", last: "Kitubu", table: "10" }
];
